//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Elicite
//  @ File Name : AutenticacaoInvalidaException.cs
//  @ Date : 18/11/2007
//  @ Author : 
//
//
using System;
using System.Runtime.Serialization;

namespace Cefet.Elicite.Dominio
{
	/// <summary>
	///  Classe de exceção das classes utilitárias da camada web.
	/// 	///
	/// </summary>
    public class AutenticacaoInvalidaException : ApplicationException
	{
		/// <summary>
		/// Construtor padrão.
		/// </summary>
		public AutenticacaoInvalidaException()
			:base("Usuário ou seja inválida.")
		{
		}
		/// <summary>
		/// Construtor.
		/// </summary>
		/// <param name="message">Mensagem com descrição do erro</param>
		public AutenticacaoInvalidaException(string message)
			:base(message)
		{ 
		}
		/// <summary>
		/// Construtor.
		/// </summary>
		/// <param name="message">Mensagem com descrição do erro</param>
		/// <param name="inner">Objeto que gerou a exceção original</param>
		public AutenticacaoInvalidaException(string message, Exception inner)
			:base(message, inner)
		{
		}

        public AutenticacaoInvalidaException(SerializationInfo info, StreamingContext context)
            : base(info, context)
        { 
       
        
        }
        public override void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
        {
            base.GetObjectData(info, context);
         
        }
	}
}