//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Elicite
//  @ File Name : IRepositoryTipoFluxo.cs
//  @ Date : 18/11/2007
//  @ Author : 
//
//


namespace Cefet.Elicite.Dominio
{
	public interface IRepositoryTipoFluxo : IRepository 
	{
	}
}
