//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Elicite
//  @ File Name : IRepositoryCasoDeUso.cs
//  @ Date : 18/11/2007
//  @ Author : 
//
//


namespace Cefet.Elicite.Dominio
{
	public interface IRepositoryCasoDeUso : IRepository 
	{
		/// <summary>
		///  Busca todos os objetos do domínio especificado
		///         ///
		/// </summary>
		System.Collections.ICollection GetAllByProjeto(Projeto projeto);
		/// <summary>
		///  Busca todos os objetos do domínio especificado
		///         ///
		/// </summary>
        System.Collections.ICollection GetAllByProjetoNotInThis(Projeto projeto, System.Collections.ICollection casosDeUso);
        int GetMaxCodigo(int codigoProjeto);
        System.Collections.ICollection GetAllByProjetoOrderByCodigoCasoUso(Projeto projeto);
	}
}
