//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Elicite
//  @ File Name : IRepositoryRequisito.cs
//  @ Date : 18/11/2007
//  @ Author : 
//
//

		
namespace Cefet.Elicite.Dominio
{
	public interface IRepositoryRequisito : IRepository 
	{
		/// <summary>
		///  Busca todos os objetos do domínio especificado
		///         ///
		/// </summary>
		System.Collections.ICollection GetAllFuctionalsByProjeto(Projeto projeto);
		/// <summary>
		///  Busca todos os objetos do domínio especificado
		///         ///
		/// </summary>
		System.Collections.ICollection GetAllNonFuctionalsByProjeto(Projeto projeto);
		/// <summary>
		///  Busca todos os objetos do domínio especificado
		///         ///
		/// </summary>
		System.Collections.ICollection GetAllByProjeto(IEntity obj, Projeto projeto);
        int GetMaxCodigo(int codigoProjeto, int codigoTipoRequisito);
        System.Collections.ICollection GetAllByProjetoOrderByTypeAndCodigo(Projeto projeto);
	}
}
