//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Elicite
//  @ File Name : IRepositoryProjeto.cs
//  @ Date : 18/11/2007
//  @ Author : 
//
//


namespace Cefet.Elicite.Dominio
{
	public interface IRepositoryProjeto : IRepository 
	{
        System.Collections.ICollection GetAllByUsuario(Usuario usuario);
	}
}
