//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Elicite
//  @ File Name : ServicoUsuario.cs
//  @ Date : 18/11/2007
//  @ Author : 
//
//
using System;
using System.Collections;

namespace Cefet.Elicite.Dominio
{
	public class ServicoUsuario 
	{
		private IRepositoryUsuario repositorioUsuarios;

        public ServicoUsuario()
        { 
            //Instancia repositório
        }
        
        /// <summary>
		///  
		///         ///
		/// </summary>
        /// 

		public IRepositoryUsuario RepositorioUsuarios
		{
			get
			{
                return repositorioUsuarios;
			}
		}
	}
}
